# Generated by Django 3.2.7 on 2021-10-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='업로드파일'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y_%m_%d', verbose_name='업로드이미지'),
        ),
    ]
